env                = "production"
location           = "europe-west1"
region             = "europe-west"
image_url          = "gcr.io/google-samples/hello-app:1.0"
service_account_id = "sa"
owner              = "samy.mokhtari213@gmail.com"
repository_id      = "docker-repository"
