env                = "production"
location           = "europe-west1"
region             = "europe-west"
service_account_id = "sa"
owner              = "samy.mokhtari213@gmail.com"
repository_id      = "docker-repository"
project_name       = "Stay"
